from typing import Any

#########################################
# --- Create Search Request Fixtures ----
#########################################

QUERY = {
    "param_name": "query",
    "param_type": str,
    "param_values": {
        "valids": [
            "Best Answer Engine Optimization startups",
            "OpenAI Sora shutdown analysis",
            "AI agent frameworks",
            "What are the latest Python web scraping libraries?",
            "best vector databases comparison",
        ],
        "invalids": [1000, {"invalid": "object"}, None, ""],
    },
}

MINIMAL_REQUEST_BODY = {
    "query": QUERY["param_values"]["valids"][0],
}

LIMIT = {
    "param_name": "limit",
    "param_type": int,
    "param_values": {
        "valids": [1, 5, 12, 20, 25],
        "invalids": [0, 26, -1, 100],
    },
}

INCLUDE_DOMAINS = {
    "param_name": "include_domains",
    "param_type": list,
    "param_values": {
        "valids": [
            ["bbc.com"],
            ["nytimes.com", "wsj.com"],
            ["bbc.com", "nytimes.com", "wsj.com"],
            [],
        ],
        "invalids": ["bbc.com", 1000, {"key": "value"}],
    },
}

EXCLUDE_DOMAINS = {
    "param_name": "exclude_domains",
    "param_type": list,
    "param_values": {
        "valids": [
            ["pinterest.com"],
            ["pinterest.com", "quora.com"],
            [],
        ],
        "invalids": ["pinterest.com", 1000, {"key": "value"}],
    },
}

SCRAPE_OPTIONS: dict[str, Any] = {
    "param_name": "scrape_options",
    "param_type": dict,
    "param_values": {
        "valids": [
            None,
            {"formats": ["markdown"]},
            {"formats": ["html"]},
            {"formats": ["html", "markdown"]},
            {"formats": ["markdown"], "timeout": 25},
            {"formats": ["markdown"], "remove_css_selectors": "default", "timeout": 25},
            {"formats": ["markdown"], "remove_css_selectors": "none", "timeout": 60},
            {"formats": ["markdown"], "timeout": 1},
        ],
        "invalids": [
            "invalid_string",
            1000,
            {"formats": ["json"]},                 # only html/markdown allowed
            {"formats": ["text"]},                 # only html/markdown allowed
            {"formats": []},                       # must be non-empty
            {"formats": ["markdown"], "timeout": 0},
            {"formats": ["markdown"], "timeout": 61},
            {"formats": ["markdown"], "timeout": -5},
        ],
    },
}

# =============================================================================
# --- Get Search Request Fixtures ---
# =============================================================================

GET_SEARCH_REQUEST_ID = {
    "param_name": "search_id",
    "param_type": str,
    "param_values": {
        # "valids" is dynamic - generated by creating a search first
        "invalids": ["non_existing_search_id"],
    },
}
