name: Setup Poetry
description: Setup Poetry with caching

inputs:
  python-version:
    description: Python version for cache key
    required: true

runs:
  using: composite
  steps:
    - name: Install Poetry
      uses: abatilo/actions-poetry@v4

    - name: Setup local virtual environment
      shell: bash
      run: |
        poetry config virtualenvs.create true --local
        poetry config virtualenvs.in-project true --local

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      shell: bash
      with:
        path: ./.venv
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('poetry.lock') }}

    - name: Install the project dependencies
      shell: bash
      run: poetry install --no-interaction
